POST http://localhost:4321/employees HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "Roxy": "roxy",
}

###
PUT http://localhost:4321/employees?id=1 HTTP/1.1
Content-Type: application/json

{
    "name": "new matrix",
        "new": 1
}

###
DELETE  http://localhost:4321/employees?id=1 HTTP/1.1

###
GET http://localhost:4321/ HTTP/1.1